### PR TITLE
feat(SCT-377): remove Warning Notes feature flag

### PR DESCRIPTION
**Pull request by chrishutchinson**
**What**  
Removes the feature flag for Warning Notes. This will make it available to everyone.

**Why**  
[SCT-377](https://hackney.atlassian.net/browse/SCT-377)

### CODE REVIEW

**Review by Renny4Real — COMMENTED** [review]
I might have tested it wrong, but I can't see the form name in the dropdown menu when I'm a CFS user. 🤔 
I can see it when I'm an ASC user.

**Comment by chrishutchinson** [comment]
> I might have tested it wrong, but I can't see the form name in the dropdown menu when I'm a CFS user. 🤔
> I can see it when I'm an ASC user.

Interesting, let me investigate!

**Comment by chrishutchinson** [comment]
@Renny4Real excellent spot there, I've fixed and added new tests to confirm the behaviour. All in https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/459/commits/ca73c9166da1835aa4db4046365b46d8c820cb8d

**Review by Renny4Real — APPROVED** [review]
🎉

**Pull request merged**
